#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm#!/bin/bash
ls -xapm
